create table customers
(
    id          bigint generated by default as identity
        primary key,
    phone       varchar(20)
        unique,
    first_name  varchar(50) not null,
    last_name   varchar(50) not null,
    middle_name varchar(50),
    email       varchar(100)
        constraint ukrfbvkrffamfql7cjmen8v976v
            unique
);

alter table customers
    owner to postgres;

create table product_categories
(
    id   bigint generated by default as identity
        primary key,
    name varchar(50) not null
        unique
);

alter table product_categories
    owner to postgres;

create table products
(
    availability        boolean        not null,
    price               numeric(10, 2) not null,
    quantity            integer        not null,
    id                  bigint generated by default as identity
        primary key,
    product_category_id bigint         not null
        constraint fke05mpyhp4howtq8q4s65wm3q8
            references product_categories,
    article             varchar(50)    not null
        unique,
    description         text,
    image_url           varchar(255),
    name                varchar(255)   not null
);

alter table products
    owner to postgres;

create table users
(
    blocked     boolean      not null,
    customer_id bigint       not null
        unique
        constraint fkchxdoybbydcaj5smgxe0qq5mk
            references customers,
    id          bigint generated by default as identity
        primary key,
    username    varchar(50)  not null
        unique,
    password    varchar(255) not null,
    role        varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying])::text[])),
    email       varchar(100)
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique
);

alter table users
    owner to postgres;

create table carts
(
    total   numeric(10, 2) not null,
    id      bigint generated by default as identity
        primary key,
    user_id bigint         not null
        unique
        constraint fkb5o626f86h46m4s7ms6ginnop
            references users
);

alter table carts
    owner to postgres;

create table cart_items
(
    quantity   integer not null,
    cart_id    bigint  not null
        constraint fkpcttvuq4mxppo8sxggjtn5i2c
            references carts,
    id         bigint generated by default as identity
        primary key,
    product_id bigint  not null
        constraint fk1re40cjegsfvw58xrkdp6bac6
            references products
);

alter table cart_items
    owner to postgres;

create table orders
(
    seen         boolean        not null,
    total        numeric(10, 2) not null,
    created_at   timestamp(6)   not null,
    id           bigint generated by default as identity
        primary key,
    user_id      bigint         not null
        constraint fk32ql8ubntj5uh44ph9659tiih
            references users,
    order_number varchar(12)    not null
        unique,
    pay_method   varchar(20),
    station      varchar(200),
    status       varchar(255)   not null
        constraint orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))
);

alter table orders
    owner to postgres;

create table order_items
(
    price      numeric(10, 2) not null,
    quantity   integer        not null,
    id         bigint generated by default as identity
        primary key,
    order_id   bigint         not null
        constraint fkbioxgbv59vetrxe0ejfubep1w
            references orders,
    product_id bigint         not null
        constraint fkocimc7dtr037rh4ls4l95nlfi
            references products
);

alter table order_items
    owner to postgres;

create table service_requests
(
    seen           boolean      not null,
    created_at     timestamp(6) not null,
    id             bigint generated by default as identity
        primary key,
    scheduled_at   timestamp(6),
    user_id        bigint
        constraint fkdnrpkrvtepdqqcxg1nqiq5edt
            references users,
    phone          varchar(20)  not null,
    city           varchar(100) not null,
    customer_name  varchar(100) not null,
    description    varchar(1000),
    payment_method varchar(255)
        constraint service_requests_payment_method_check
            check ((payment_method)::text = ANY
                   ((ARRAY ['CARD'::character varying, 'CASH'::character varying])::text[])),
    status         varchar(255) not null
        constraint service_requests_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACCEPTED'::character varying, 'SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))
);

alter table service_requests
    owner to postgres;

create table work_service_categories
(
    id   bigint generated by default as identity
        primary key,
    name varchar(50) not null
        unique
);

alter table work_service_categories
    owner to postgres;

create table work_services
(
    price                    numeric(10, 2) not null,
    id                       bigint generated by default as identity
        primary key,
    work_service_category_id bigint         not null
        constraint fkjvptai4g1kswvuatsanf3hm5x
            references work_service_categories,
    working_hours            varchar(100),
    description              text,
    name                     varchar(255)   not null
);

alter table work_services
    owner to postgres;

create table vehicles
(
    id           bigint generated by default as identity
        primary key,
    brand        varchar(255) not null,
    model        varchar(255) not null,
    modification varchar(255) not null,
    year         integer      not null
);

alter table vehicles
    owner to postgres;

create table vehicle_product
(
    product_id bigint not null
        constraint fkgqvrgtsxqrniq8twwvhh6mx6f
            references products,
    vehicle_id bigint not null
        constraint fkdntb38u9hpyjlgp8hwe2jbwi4
            references vehicles
);

alter table vehicle_product
    owner to postgres;

create table spring_session
(
    primary_id            char(36) not null
        constraint spring_session_pk
            primary key,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100)
);

alter table spring_session
    owner to postgres;

create unique index spring_session_ix1
    on spring_session (session_id);

create index spring_session_ix2
    on spring_session (expiry_time);

create index spring_session_ix3
    on spring_session (principal_name);

create table spring_session_attributes
(
    session_primary_id char(36)     not null
        constraint spring_session_attributes_fk
            references spring_session
            on delete cascade,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
    constraint spring_session_attributes_pk
        primary key (session_primary_id, attribute_name)
);

alter table spring_session_attributes
    owner to postgres;

create table reviews
(
    id                 bigint generated by default as identity
        primary key,
    content            text         not null,
    created_at         timestamp(6) not null,
    target_id          bigint       not null,
    target_type        varchar(20)  not null
        constraint reviews_target_type_check
            check ((target_type)::text = ANY
                   ((ARRAY ['PRODUCT'::character varying, 'SERVICE'::character varying])::text[])),
    parent_id          bigint
        constraint fk7qpkv66dxpmph7fcilu9ucqtc
            references reviews,
    reply_to_review_id bigint
        constraint fknymn89dygwh8jmdqt0r2r8qey
            references reviews,
    reply_to_user_id   bigint
        constraint fk26mid8sk65rdq22x4pwi8swba
            references users,
    user_id            bigint       not null
        constraint fkcgy7qjc1r99dp117y9en6lxye
            references users
);

alter table reviews
    owner to postgres;

create table review_likes
(
    id        bigint generated by default as identity
        primary key,
    review_id bigint not null
        constraint fkm2uonfg8ky6jwtu6iugkilox8
            references reviews,
    user_id   bigint not null
        constraint fknual15vv88tiqnwmi60tb2l8d
            references users,
    constraint ukb74o5l2fmrgqg556d9nyop0ns
        unique (user_id, review_id)
);

alter table review_likes
    owner to postgres;

create table review_notifications
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    seen       boolean      not null,
    review_id  bigint       not null
        constraint fk5jyn3gh3nv6o0ts94uvau3c4e
            references reviews,
    user_id    bigint       not null
        constraint fke9d6lv1hbjyk0pbivt5sdby3t
            references users,
    type       varchar(20)
);

alter table review_notifications
    owner to postgres;
