spring.application.name=TireVault
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/TireVaultRestApi
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

spring.session.servlet.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=7d

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.flyway.locations=classpath:db

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=course.project.ua.tirevault.Controllers.RESTful_API
spring.session.cookie.name=SESSION
server.servlet.session.cookie.same-site=lax

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.config.import=optional:file:.env